language: cpp
compiler:
    - clang
before_install:
    - openssl aes-256-cbc -K $encrypted_f770e278aa8f_key -iv $encrypted_f770e278aa8f_iv -in config/travisci_rsa.enc -out config/travisci_rsa -d
    - chmod 0600 config/travisci_rsa
    - cp config/travisci_rsa ~/.ssh/id_rsa
addons:
    apt:
        source:
        - debian-sid
        packages:
        - doxygen
        - graphviz
before_script:
    - cd build
    - cmake ..
script: make && make test
after_success:
    - ../config/publish-doxygen
notifications:
    slack:
        secure: QE5iXu2KnQZGsyac86j6xdaEvLTAjk0ONcSTH4hpGgiMnQ4kKRvWecfLod7h4OQkgwYVta+mnbuFxVmHPw6VozGsnb/WAV41cIiO3qVHjxl11FZUXpwE2cgyeNcGUlx/BMUC9i7n5ksIlD8uNa1UtpKDwVU/4VYy7ul1VVf0D/U=
sudo: false
